apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: t0ztzaw9i-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: t0ztzaw9i-go 
  name: t0ztzaw9i-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: t0ztzaw9i-go 
